### ISSUE TITLE
Need Assistant

### ISSUE THREAD

**Issue by MEAPPU** [akash-1618/Plant-Nursery-Management-System#2]
Heyy Akash.. Need help in clearing the errors in operation class please help us here... All date related functions are showing errors could u please guide here how can we resolve those things

**Comment by akash-1618** [comment]
Hello Anon.
1) This is one project I absolutely cannot help you with even if I want to. The two reasons for that being - I am not proficient with Java and the second being the same issue you are facing, the project always gives out dependency errors.

2) I remember taking backups everyday even after minimal edits and storing them because I was afraid that the project will stop running because of dependency issues the moment I blink. Well, you can upload the code on github as an alternative but myself felt that it was more convenient to store them as zips. The very reason for this behaviour was that the project had failed five times before and I had to start again(five times) from scratch.
So if you decide to continue with this project, I'd suggest you to do the same.

3) Can you still give me a detailed structure of the error? As in, the code/name of the error. The least I can do is try to figure out a solution for the same.

4) If it's an academic project you're doing, an advice would be to skip this and look for some other one. This one is a pain in the back of the head and will get you nowhere because it might stop working the moment you turn off your system. Extremely unreliable.

5) If you are doing it for fun, read 3.

But I warn you, if this is for academics and if you text me persistently to solve your problem then I would have no choice but to avoid you.

Have a nice day
